/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "error-container": "#ffdad6",
          "tertiary-fixed": "#ffdcbe",
          "surface-container-high": "#d5ecf8",
          "background": "#f3faff",
          "inverse-surface": "#1e333c",
          "on-surface": "#071e27",
          "on-tertiary-container": "#ffc388",
          "on-secondary-fixed": "#002204",
          "primary-fixed": "#d9e2ff",
          "on-primary-fixed-variant": "#00419c",
          "error": "#ba1a1a",
          "on-tertiary": "#ffffff",
          "outline": "#737784",
          "surface-tint": "#1d59c1",
          "on-primary-container": "#bcceff",
          "on-secondary-container": "#00731e",
          "secondary-container": "#91f78e",
          "surface-container": "#dbf1fe",
          "on-secondary-fixed-variant": "#005313",
          "on-tertiary-fixed-variant": "#693c00",
          "surface-dim": "#c7dde9",
          "surface-container-low": "#e6f6ff",
          "primary": "#003c90",
          "on-tertiary-fixed": "#2c1600",
          "on-primary-fixed": "#001945",
          "tertiary": "#613600",
          "on-background": "#071e27",
          "surface-container-lowest": "#ffffff",
          "inverse-primary": "#b0c6ff",
          "secondary-fixed": "#94f990",
          "surface-variant": "#cfe6f2",
          "inverse-on-surface": "#dff4ff",
          "primary-container": "#0f52ba",
          "on-surface-variant": "#434653",
          "on-error": "#ffffff",
          "secondary-fixed-dim": "#78dc77",
          "secondary": "#006e1c",
          "tertiary-fixed-dim": "#ffb870",
          "on-secondary": "#ffffff",
          "tertiary-container": "#814b00",
          "on-primary": "#ffffff",
          "primary-fixed-dim": "#b0c6ff",
          "surface": "#f3faff",
          "on-error-container": "#93000a",
          "outline-variant": "#c3c6d5",
          "surface-container-highest": "#cfe6f2",
          "surface-bright": "#f3faff"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "sm": "12px",
          "xs": "4px",
          "md": "24px",
          "margin": "32px",
          "base": "8px",
          "xl": "64px",
          "gutter": "24px",
          "lg": "40px"
      },
      "fontFamily": {
          "label-md": ["Inter"],
          "headline-md": ["Inter"],
          "body-lg": ["Inter"],
          "label-sm": ["Inter"],
          "headline-xl": ["Inter"],
          "headline-lg": ["Inter"],
          "body-md": ["Inter"]
      },
      "fontSize": {
          "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
          "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
          "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "500" }],
          "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
