/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "error-container": "#ffdad6",
          "tertiary-fixed": "#ffdcbe",
          "surface-container-high": "#edeef1",
          "background": "#f9f9fc",
          "inverse-surface": "#2e3133",
          "on-surface": "#191c1e",
          "on-tertiary-container": "#eab66d",
          "on-secondary-fixed": "#002020",
          "primary-fixed": "#cbe6ff",
          "on-primary-fixed-variant": "#0e4b6e",
          "error": "#ba1a1a",
          "on-tertiary": "#ffffff",
          "outline": "#72787f",
          "surface-tint": "#2f6388",
          "on-primary-container": "#94c5ee",
          "on-secondary-container": "#007070",
          "secondary-container": "#8cf3f3",
          "surface-container": "#edeef1",
          "on-secondary-fixed-variant": "#004f4f",
          "on-tertiary-fixed-variant": "#633f00",
          "surface-dim": "#d9dadd",
          "surface-container-low": "#f3f3f7",
          "primary": "#003b5a",
          "on-tertiary-fixed": "#291800",
          "on-primary-fixed": "#001e30",
          "tertiary": "#4d3100",
          "on-background": "#191c1e",
          "surface-container-lowest": "#ffffff",
          "inverse-primary": "#9bccf6",
          "secondary-fixed": "#8cf3f3",
          "surface-variant": "#e2e2e6",
          "inverse-on-surface": "#f0f0f4",
          "primary-container": "#1a5276",
          "on-surface-variant": "#41474e",
          "on-error": "#ffffff",
          "secondary-fixed-dim": "#6fd7d6",
          "secondary": "#006a6a",
          "tertiary-fixed-dim": "#f2bd74",
          "on-secondary": "#ffffff",
          "tertiary-container": "#6b4604",
          "on-primary": "#ffffff",
          "primary-fixed-dim": "#9bccf6",
          "surface": "#f9f9fc",
          "on-error-container": "#93000a",
          "outline-variant": "#c1c7cf",
          "surface-container-highest": "#e2e2e6",
          "surface-bright": "#f9f9fc"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "sm": "12px",
          "xs": "4px",
          "md": "24px",
          "margin": "32px",
          "base": "8px",
          "xl": "64px",
          "gutter": "24px",
          "lg": "40px"
      },
      "fontFamily": {
          "label-md": ["Inter"],
          "headline-md": ["Inter"],
          "body-lg": ["Inter"],
          "label-sm": ["Inter"],
          "headline-xl": ["Inter"],
          "headline-lg": ["Inter"],
          "body-md": ["Inter"]
      },
      "fontSize": {
          "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
          "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
          "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "500" }],
          "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
